name: code_quest
description: "A quiz app for programming languages..."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.5.1
  firebase_auth: ^5.2.1
  firebase_database: ^11.1.2
  cloud_firestore: ^5.4.1
  google_sign_in: ^6.2.1
  firebase_core: ^3.4.1
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/raw/